repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.11
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pytest-check
        name: Run tests after formatting and dependency changes
        entry: uv run --frozen pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]